#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WRAPPER="$PROJECT_ROOT/dc-runner"
BIN_DIR="$PROJECT_ROOT/bin"

rm -f "$BIN_DIR"/*

for filepath in $(find "$PROJECT_ROOT" -type f -name 'config.sh'); do
    dir=$(dirname "$filepath")
    tool_name="${dir##*/}"
    ln -sf "../dc-runner" "$BIN_DIR/$tool_name"
done
